# Introduction to Python

### Cells and running lines of python code

In [1]:
2+2+2

6

In [2]:
print('Hello')

Hello

### Creating comments within python

Using Markdown

In [3]:
# inline comments

In [4]:
print('Hello') #simple print statement

Hello

In [5]:
print('Hello') #use 'ctrl + /' (windows) or 'cmd + /' (mac)

Hello

### Shortcuts

You can see all short cuts in the help menu

A few important ones:

- Shift + Enter -> run and go to the next cell
- Ctrl + Enter -> run and stay on the same cell
- Alt + Enter or Option + Enter -> run and add a new cell
- Tab -> autofill or gives options
- Shift + Tab -> provides documentation

In [6]:
2*2

4

In [7]:
print('hello')

hello

### Data types and Variables

Most common data types in python
- Numeric - int (whole numbers), float (decimals)
- String 
- Boolean

In [8]:
a = 5 #in python you do not need to declare variables or provide the data type for variables
print(a)
print('a is of type',type(a)) #we can see the data type of variables using type

5
a is of type <class 'int'>

In [9]:
b = 2.1
print(b)
print('b is of type',type(b))

2.1
b is of type <class 'float'>

In [10]:
c = a/b
print('c is of type',type(c), 'and its value is',c)
c = float(a)/b
print('c is of type',type(c), 'and its value is',c)

c is of type <class 'float'> and its value is 2.380952380952381
c is of type <class 'float'> and its value is 2.380952380952381

In [11]:
welcome = 'Welcome to ARTI 300'
print(welcome)
print(type(welcome))

Welcome to ARTI 300
<class 'str'>

In [12]:
# there are many string functions available 
print(welcome.islower())
print(welcome.upper())

False
WELCOME TO ARTI 300

In [13]:
var1 = 1

In [14]:
print(var1) 
type(var1)

1

int

In [15]:
var1 = str(var1)

In [16]:
print(var1) 
type(var1)

1

str

In [17]:
x = True
print(x)

y = welcome.islower()
print(y)

True
False

### Collections of variables
There are 4 main types of collections of variables in python
- list - [ ] - can be of differnt types, ordered, changeable, allows duplicates, indexed by 0
- tuple - ( ) - can't change values
- set - { } - unordered and can't have duplicates
- dictionary - { } - unordered and indexed by strings

In [18]:
list1 = ['ARTI300',6,12.3,'73']
print(list1)
print(list1[0])
print(type(list1[3]))
print(len(list1))
print(list1[1:3]) #first number is inclusive, second is exclusive

['ARTI300', 6, 12.3, '73']
ARTI300
<class 'str'>
4
[6, 12.3]

In [19]:
# changing list values
list1[2] = 24.5
list1.append('added value') # adding an item to the list
print(list1)
list1.pop(1) # removing an item from the list
print(list1)

['ARTI300', 6, 24.5, '73', 'added value']
['ARTI300', 24.5, '73', 'added value']

In [20]:
# copying lists
list2 = list1
print(list2)
print(list1)
list2.append(14)
print(list2)
print(list1)

['ARTI300', 24.5, '73', 'added value']
['ARTI300', 24.5, '73', 'added value']
['ARTI300', 24.5, '73', 'added value', 14]
['ARTI300', 24.5, '73', 'added value', 14]

In [21]:
# we must use the copy method to prevent this 
list3 = list1.copy()
print(list3)
print(list1)
list3[4] = 41
print(list3)
print(list1)

['ARTI300', 24.5, '73', 'added value', 14]
['ARTI300', 24.5, '73', 'added value', 14]
['ARTI300', 24.5, '73', 'added value', 41]
['ARTI300', 24.5, '73', 'added value', 14]

In [22]:
tuple1 = (12,42,11,99,2351)
print(tuple1)
print(tuple1[2])

(12, 42, 11, 99, 2351)
11

In [23]:
# it is not possible to change entries in a touple
tuple1[2] = 5

TypeError: 'tuple' object does not support item assignment

In [27]:
set1 = {3.1, 'ARTI300', 5}
print(set1)

{'ARTI300', 3.1, 5}

In [29]:
print('ARTI300' in set1)

True

In [30]:
dict1 = {
    "course": "ARTI200",
    "semester": "Spring 23",
    "location": "BUS110",
    "classsize": 20
}
print(dict1)
print(dict1["course"], dict1["classsize"])

{'course': 'ARTI200', 'semester': 'Spring 23', 'location': 'BUS110', 'classsize': 20}
ARTI200 20

In [31]:
dict1['time'] = '1:30pm'
print(dict1)

{'course': 'ARTI200', 'semester': 'Spring 23', 'location': 'BUS110', 'classsize': 20, 'time': '1:30pm'}

### if statement

In [32]:
i = 7
if i > 10:
    print(i,'is greater than 10')
elif i < 5:
    print(i,'is less than 5')
else:
    print(i,'is between 5 and 10')

7 is between 5 and 10

### for loop

In [33]:
print(list1)

['ARTI300', 24.5, '73', 'added value', 14]

In [34]:
for i in list1:
    print(i)

ARTI300
24.5
73
added value
14

In [35]:
for i in range(5):
    print(i)

0
1
2
3
4

In [36]:
for i in range(3,7):
    print(i)

3
4
5
6

In [37]:
for i in range(1,20,4):
    print(i)

1
5
9
13
17

### while loop

In [38]:
i = 0
while i <= 10:
    print(i)
    i = i+1

0
1
2
3
4
5
6
7
8
9
10

### user defined functions

In [39]:
# define a function that takes an input, squares it, adds 7, then returns the answer

def ConvertStringToUpper(s):
    """    documentation string example
    """
    ToUpper = s.upper()
    return ToUpper

print(ConvertStringToUpper("Welcome to ARTI300"))
print(ConvertStringToUpper.__doc__)

WELCOME TO ARTI300
    documentation string example

In [40]:
ConvertStringToLower = lambda s: s.lower()
print(ConvertStringToLower("Welcome to ARTI300"))

welcome to arti300

## Load csv file

In [41]:
# install and import necessary libraries
import pandas as pd                                     # Import pandas

In [42]:
# Load titanic_passenger_list.csv into dataframe
df = pd.read_csv("titanic_passenger_list.csv")

In [43]:
# view the first 10 rows of the dataframe
df.head(10)

,pclass,survived,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest
0,1,1,"Allen, Miss. Elisabeth Walton",female,29.00,0,0,24160,211.3375,B5,S,2,NaN,"St Louis, MO"
1,1,1,"Allison, Master. Hudson Trevor",male,0.92,1,2,113781,151.5500,C22 C26,S,11,NaN,"Montreal, PQ / Chesterville, ON"
2,1,0,"Allison, Miss. Helen Loraine",female,2.00,1,2,113781,151.5500,C22 C26,S,NaN,NaN,"Montreal, PQ / Chesterville, ON"
3,1,0,"Allison, Mr. Hudson Joshua Creighton",male,30.00,1,2,113781,151.5500,C22 C26,S,NaN,135.0,"Montreal, PQ / Chesterville, ON"
4,1,0,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.00,1,2,113781,151.5500,C22 C26,S,NaN,NaN,"Montreal, PQ / Chesterville, ON"
5,1,1,"Anderson, Mr. Harry",male,48.00,0,0,19952,26.5500,E12,S,3,NaN,"New York, NY"
6,1,1,"Andrews, Miss. Kornelia Theodosia",female,63.00,1,0,13502,77.9583,D7,S,10,NaN,"Hudson, NY"
7,1,0,"Andrews, Mr. Thomas Jr",male,39.00,0,0,112050,0.0000,A36,S,NaN,NaN,"Belfast, NI"
8,1,1,"Appleton, Mrs. Edward Dale (Charlotte Lamson)",female,53.00,2,0,11769,51.4792,C101,S,D,NaN,"Bayside, Queens, NY"
9,1,0,"Artagaveytia, Mr. Ramon",male,71.00,0,0,PC 17609,49.5042,NaN,C,NaN,22.0,"Montevideo, Uruguay"

In [44]:
# view the first 10 rows of the dataframe
df.head(10)

,pclass,survived,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest
0,1,1,"Allen, Miss. Elisabeth Walton",female,29.00,0,0,24160,211.3375,B5,S,2,NaN,"St Louis, MO"
1,1,1,"Allison, Master. Hudson Trevor",male,0.92,1,2,113781,151.5500,C22 C26,S,11,NaN,"Montreal, PQ / Chesterville, ON"
2,1,0,"Allison, Miss. Helen Loraine",female,2.00,1,2,113781,151.5500,C22 C26,S,NaN,NaN,"Montreal, PQ / Chesterville, ON"
3,1,0,"Allison, Mr. Hudson Joshua Creighton",male,30.00,1,2,113781,151.5500,C22 C26,S,NaN,135.0,"Montreal, PQ / Chesterville, ON"
4,1,0,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.00,1,2,113781,151.5500,C22 C26,S,NaN,NaN,"Montreal, PQ / Chesterville, ON"
5,1,1,"Anderson, Mr. Harry",male,48.00,0,0,19952,26.5500,E12,S,3,NaN,"New York, NY"
6,1,1,"Andrews, Miss. Kornelia Theodosia",female,63.00,1,0,13502,77.9583,D7,S,10,NaN,"Hudson, NY"
7,1,0,"Andrews, Mr. Thomas Jr",male,39.00,0,0,112050,0.0000,A36,S,NaN,NaN,"Belfast, NI"
8,1,1,"Appleton, Mrs. Edward Dale (Charlotte Lamson)",female,53.00,2,0,11769,51.4792,C101,S,D,NaN,"Bayside, Queens, NY"
9,1,0,"Artagaveytia, Mr. Ramon",male,71.00,0,0,PC 17609,49.5042,NaN,C,NaN,22.0,"Montevideo, Uruguay"

In [45]:
# view the last 10 rows of the dataframe
df.tail(10)

,pclass,survived,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest
1299,3,0,"Yasbeck, Mr. Antoni",male,27.0,1,0,2659,14.4542,NaN,C,C,NaN,NaN
1300,3,1,"Yasbeck, Mrs. Antoni (Selini Alexander)",female,15.0,1,0,2659,14.4542,NaN,C,NaN,NaN,NaN
1301,3,0,"Youseff, Mr. Gerious",male,45.5,0,0,2628,7.2250,NaN,C,NaN,312.0,NaN
1302,3,0,"Yousif, Mr. Wazli",male,NaN,0,0,2647,7.2250,NaN,C,NaN,NaN,NaN
1303,3,0,"Yousseff, Mr. Gerious",male,NaN,0,0,2627,14.4583,NaN,C,NaN,NaN,NaN
1304,3,0,"Zabour, Miss. Hileni",female,14.5,1,0,2665,14.4542,NaN,C,NaN,328.0,NaN
1305,3,0,"Zabour, Miss. Thamine",female,NaN,1,0,2665,14.4542,NaN,C,NaN,NaN,NaN
1306,3,0,"Zakarian, Mr. Mapriededer",male,26.5,0,0,2656,7.2250,NaN,C,NaN,304.0,NaN
1307,3,0,"Zakarian, Mr. Ortin",male,27.0,0,0,2670,7.2250,NaN,C,NaN,NaN,NaN
1308,3,0,"Zimmerman, Mr. Leo",male,29.0,0,0,315082,7.8750,NaN,S,NaN,NaN,NaN

In [46]:
# use shape to determine how many rows and columns are in the dataframe
df.shape

(1309, 14)

In [47]:
# information of all columns in the dataframe
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1309 entries, 0 to 1308
Data columns (total 14 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   pclass     1309 non-null   int64
 1   survived   1309 non-null   int64
 2   name       1309 non-null   object
 3   sex        1309 non-null   object
 4   age        1046 non-null   float64
 5   sibsp      1309 non-null   int64
 6   parch      1309 non-null   int64
 7   ticket     1309 non-null   object
 8   fare       1308 non-null   float64
 9   cabin      295 non-null    object
 10  embarked   1307 non-null   object
 11  boat       486 non-null    object
 12  body       121 non-null    float64
 13  home.dest  745 non-null    object
dtypes: float64(3), int64(4), object(7)
memory usage: 143.3+ KB

In [48]:
# find the datatype of each column
df.dtypes

pclass         int64
survived       int64
name          object
sex           object
age          float64
sibsp          int64
parch          int64
ticket        object
fare         float64
cabin         object
embarked      object
boat          object
body         float64
home.dest     object
dtype: object

In [49]:
# find the number of non null values for each column
df.count()

pclass       1309
survived     1309
name         1309
sex          1309
age          1046
sibsp        1309
parch        1309
ticket       1309
fare         1308
cabin         295
embarked     1307
boat          486
body          121
home.dest     745
dtype: int64

In [50]:
# find statistical information for the numeric columns
df.describe()

,pclass,survived,age,sibsp,parch,fare,body
count,1309.000000,1309.000000,1046.000000,1309.000000,1309.000000,1308.000000,121.000000
mean,2.294882,0.381971,29.881138,0.498854,0.385027,33.295479,160.809917
std,0.837836,0.486055,14.413493,1.041658,0.865560,51.758668,97.696922
min,1.000000,0.000000,0.170000,0.000000,0.000000,0.000000,1.000000
25%,2.000000,0.000000,21.000000,0.000000,0.000000,7.895800,72.000000
50%,3.000000,0.000000,28.000000,0.000000,0.000000,14.454200,155.000000
75%,3.000000,1.000000,39.000000,1.000000,0.000000,31.275000,256.000000
max,3.000000,1.000000,80.000000,8.000000,9.000000,512.329200,328.000000

In [51]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
pclass,1309.0,2.294882,0.837836,1.00,2.0000,3.0000,3.000,3.0000
survived,1309.0,0.381971,0.486055,0.00,0.0000,0.0000,1.000,1.0000
age,1046.0,29.881138,14.413493,0.17,21.0000,28.0000,39.000,80.0000
sibsp,1309.0,0.498854,1.041658,0.00,0.0000,0.0000,1.000,8.0000
parch,1309.0,0.385027,0.865560,0.00,0.0000,0.0000,0.000,9.0000
fare,1308.0,33.295479,51.758668,0.00,7.8958,14.4542,31.275,512.3292
body,121.0,160.809917,97.696922,1.00,72.0000,155.0000,256.000,328.0000

In [52]:
# find unique values for a column
df.pclass.unique()

array([1, 2, 3])

In [53]:
df.sex.unique()

array(['female', 'male'], dtype=object)

In [54]:
# we can find specific statistical information for individual columns
df.age.mean()

29.881137667304014

In [55]:
df.age.max()

80.0

In [56]:
df["sex"].value_counts()

male      843
female    466
Name: sex, dtype: int64