### Loading Libraries

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', 200)

C:\Users\codyd\AppData\Local\Temp\ipykernel_13436\91579162.py:1: DeprecationWarning:
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466

  import pandas as pd

### Load Data

In [2]:
df = pd.read_csv('auto-mpg.csv')
print(f'There are {df.shape[0]} rows and {df.shape[1]} columns.')

There are 398 rows and 9 columns.

## Data Overview

In [3]:
np.random.seed(1)
df.sample(n=10)

,MPG,Cylinders,Displacement,Horsepower,Weight,Acceleration,Model year,Origin,Car name
174,18.0,6,171.0,97,2984,14.5,75,1,ford pinto
359,28.1,4,141.0,80,3230,20.4,81,2,peugeot 505s turbo diesel
250,19.4,8,318.0,140,3735,13.2,78,1,dodge diplomat
274,20.3,5,131.0,103,2830,15.9,78,2,audi 5000
283,20.2,6,232.0,90,3265,18.2,79,1,amc concord dl 6
232,16.0,8,351.0,149,4335,14.5,77,1,ford thunderbird
117,29.0,4,68.0,49,1867,19.5,73,2,fiat 128
348,37.7,4,89.0,62,2050,17.3,81,3,toyota tercel
189,15.5,8,304.0,120,3962,13.9,76,1,amc matador
106,12.0,8,350.0,180,4499,12.5,73,1,oldsmobile vista cruiser

In [4]:
df.sample(n=10)

,MPG,Cylinders,Displacement,Horsepower,Weight,Acceleration,Model year,Origin,Car name
8,14.0,8,455.0,225,4425,10.0,70,1,pontiac catalina
263,17.7,6,231.0,165,3445,13.4,78,1,buick regal sport coupe (turbo)
117,29.0,4,68.0,49,1867,19.5,73,2,fiat 128
379,36.0,4,98.0,70,2125,17.3,82,1,mercury lynx l
251,20.2,8,302.0,139,3570,12.8,78,1,mercury monarch ghia
175,29.0,4,90.0,70,1937,14.0,75,2,volkswagen rabbit
233,29.0,4,97.0,78,1940,14.5,77,2,volkswagen rabbit custom
265,17.5,8,318.0,140,4080,13.7,78,1,dodge magnum xe
47,19.0,6,250.0,100,3282,15.0,71,1,pontiac firebird
242,21.5,4,121.0,110,2600,12.8,77,2,bmw 320i

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 398 entries, 0 to 397
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   MPG           398 non-null    float64
 1   Cylinders     398 non-null    int64
 2   Displacement  398 non-null    float64
 3   Horsepower    398 non-null    object
 4   Weight        398 non-null    int64
 5   Acceleration  398 non-null    float64
 6   Model year    398 non-null    int64
 7   Origin        398 non-null    int64
 8   Car name      398 non-null    object
dtypes: float64(3), int64(4), object(2)
memory usage: 28.1+ KB

In [6]:
df.isnull().sum().sort_values(ascending=False)

MPG             0
Cylinders       0
Displacement    0
Horsepower      0
Weight          0
Acceleration    0
Model year      0
Origin          0
Car name        0
dtype: int64

In [7]:
df['Horsepower'] = df['Horsepower'].astype(str)

In [8]:
df.dtypes

MPG             float64
Cylinders         int64
Displacement    float64
Horsepower       object
Weight            int64
Acceleration    float64
Model year        int64
Origin            int64
Car name         object
dtype: object

In [9]:
df[['Make', 'Model']] = df['Car name'].str.split(" ", n=1, expand=True)

In [10]:
df.head()

,MPG,Cylinders,Displacement,Horsepower,Weight,Acceleration,Model year,Origin,Car name,Make,Model
0,18.0,8,307.0,130,3504,12.0,70,1,chevrolet chevelle malibu,chevrolet,chevelle malibu
1,15.0,8,350.0,165,3693,11.5,70,1,buick skylark 320,buick,skylark 320
2,18.0,8,318.0,150,3436,11.0,70,1,plymouth satellite,plymouth,satellite
3,16.0,8,304.0,150,3433,12.0,70,1,amc rebel sst,amc,rebel sst
4,17.0,8,302.0,140,3449,10.5,70,1,ford torino,ford,torino

In [11]:
df = df.drop('Car name', axis=1)
df['Origin'] = df['Origin'].replace({1: 'america', 2: 'europe', 3: 'asia'})
df.head()

,MPG,Cylinders,Displacement,Horsepower,Weight,Acceleration,Model year,Origin,Make,Model
0,18.0,8,307.0,130,3504,12.0,70,america,chevrolet,chevelle malibu
1,15.0,8,350.0,165,3693,11.5,70,america,buick,skylark 320
2,18.0,8,318.0,150,3436,11.0,70,america,plymouth,satellite
3,16.0,8,304.0,150,3433,12.0,70,america,amc,rebel sst
4,17.0,8,302.0,140,3449,10.5,70,america,ford,torino

In [12]:
df = pd.get_dummies(df, columns=['Origin'])
df.head()

,MPG,Cylinders,Displacement,Horsepower,Weight,Acceleration,Model year,Make,Model,Origin_america,Origin_asia,Origin_europe
0,18.0,8,307.0,130,3504,12.0,70,chevrolet,chevelle malibu,True,False,False
1,15.0,8,350.0,165,3693,11.5,70,buick,skylark 320,True,False,False
2,18.0,8,318.0,150,3436,11.0,70,plymouth,satellite,True,False,False
3,16.0,8,304.0,150,3433,12.0,70,amc,rebel sst,True,False,False
4,17.0,8,302.0,140,3449,10.5,70,ford,torino,True,False,False

In [13]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
MPG,398.0,23.514573,7.815984,9.0,17.500,23.0,29.000,46.6
Cylinders,398.0,5.454774,1.701004,3.0,4.000,4.0,8.000,8.0
Displacement,398.0,193.425879,104.269838,68.0,104.250,148.5,262.000,455.0
Weight,398.0,2970.424623,846.841774,1613.0,2223.750,2803.5,3608.000,5140.0
Acceleration,398.0,15.568090,2.757689,8.0,13.825,15.5,17.175,24.8
Model year,398.0,76.010050,3.697627,70.0,73.000,76.0,79.000,82.0

In [14]:
df.dtypes

MPG               float64
Cylinders           int64
Displacement      float64
Horsepower         object
Weight              int64
Acceleration      float64
Model year          int64
Make               object
Model              object
Origin_america       bool
Origin_asia          bool
Origin_europe        bool
dtype: object

In [15]:
df.Horsepower.unique()

array(['130', '165', '150', '140', '198', '220', '215', '225', '190',
       '170', '160', '95', '97', '85', '88', '46', '87', '90', '113',
       '200', '210', '193', '?', '100', '105', '175', '153', '180', '110',
       '72', '86', '70', '76', '65', '69', '60', '80', '54', '208', '155',
       '112', '92', '145', '137', '158', '167', '94', '107', '230', '49',
       '75', '91', '122', '67', '83', '78', '52', '61', '93', '148',
       '129', '96', '71', '98', '115', '53', '81', '79', '120', '152',
       '102', '108', '68', '58', '149', '89', '63', '48', '66', '139',
       '103', '125', '133', '138', '135', '142', '77', '62', '132', '84',
       '64', '74', '116', '82'], dtype=object)

In [16]:
df.Horsepower.value_counts()

Horsepower
150    22
90     20
88     19
110    18
100    17
75     14
95     14
105    12
70     12
67     12
65     10
97      9
85      9
80      7
145     7
140     7
92      6
68      6
78      6
84      6
?       6
72      6
180     5
71      5
86      5
115     5
130     5
60      5
170     5
175     5
83      4
120     4
76      4
165     4
52      4
190     3
125     3
215     3
48      3
63      3
112     3
225     3
96      3
69      3
74      3
129     2
98      2
198     2
53      2
81      2
79      2
153     2
58      2
62      2
87      2
46      2
160     2
155     2
139     2
66      1
149     1
132     1
64      1
116     1
77      1
89      1
142     1
135     1
138     1
133     1
103     1
107     1
108     1
102     1
220     1
113     1
200     1
210     1
193     1
54      1
208     1
137     1
158     1
167     1
94      1
230     1
49      1
91      1
122     1
61      1
93      1
148     1
152     1
82      1
Name: count, dtype: int64

In [17]:
new_df = df[(df['Horsepower'] != '?')]

In [18]:
new_df['Horsepower'] = pd.to_numeric(new_df['Horsepower'], errors='coerce')

C:\Users\codyd\AppData\Local\Temp\ipykernel_13436\463720155.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['Horsepower'] = pd.to_numeric(new_df['Horsepower'], errors='coerce')

In [19]:
df = new_df

In [20]:
df.dtypes

MPG               float64
Cylinders           int64
Displacement      float64
Horsepower          int64
Weight              int64
Acceleration      float64
Model year          int64
Make               object
Model              object
Origin_america       bool
Origin_asia          bool
Origin_europe        bool
dtype: object

In [21]:
# Split data
x = df.drop(['MPG', 'Origin_europe', 'Make', 'Model'], axis=1)
# dependent variable
y = df[['MPG']]

In [22]:
x

,Cylinders,Displacement,Horsepower,Weight,Acceleration,Model year,Origin_america,Origin_asia
0,8,307.0,130,3504,12.0,70,True,False
1,8,350.0,165,3693,11.5,70,True,False
2,8,318.0,150,3436,11.0,70,True,False
3,8,304.0,150,3433,12.0,70,True,False
4,8,302.0,140,3449,10.5,70,True,False
...,...,...,...,...,...,...,...,...
393,4,140.0,86,2790,15.6,82,True,False
394,4,97.0,52,2130,24.6,82,False,False
395,4,135.0,84,2295,11.6,82,True,False
396,4,120.0,79,2625,18.6,82,True,False
397,4,119.0,82,2720,19.4,82,True,False

In [23]:
x.isnull().sum()

Cylinders         0
Displacement      0
Horsepower        0
Weight            0
Acceleration      0
Model year        0
Origin_america    0
Origin_asia       0
dtype: int64

In [24]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.30, random_state=1)

In [25]:
# Fit model
regression_model = LinearRegression()
regression_model.fit(x_train, y_train)

LinearRegression()